name: CI UWP

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout latest
      uses: actions/checkout@v1
    
    - name: Setup Visual Studio Command Prompt
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: Build
      env:
        SOLUTION: 'App.UWP/App.UWP.csproj'
        BUILD_CONFIG: 'Release'
        BUILD_PLATFORM: 'x86|x64|ARM'
        APPX_PARAMS: '/p:AppxBundle=Always /p:UapAppxPackageBuildMode=SideloadOnly /p:AppxBundlePlatforms="%BUILD_PLATFORM%" /p:AppxPackageDir=%APPX_DIR%'
        APPX_DIR: 'App.UWP/AppxPackages'
      run: |
        REM call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat"
        echo msbuild /restore /t:Build %APPX_PARAMS% /p:Configuration=%BUILD_CONFIG% %SOLUTION%
        msbuild /restore /t:Build %APPX_PARAMS% /p:Configuration=%BUILD_CONFIG% %SOLUTION%
        
    - name: Archive app binary
      uses: actions/upload-artifact@v1
      with:
        name: $SOLUTION
        path: App.UWP/AppxPackages/*
      

        
