name: CI WPF

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout latest
      uses: actions/checkout@v1
    - name: Build
      run: |
        msbuild /restore /t:Build /p:Configuration=Release AnotherApp.WPF/AnotherApp.WPF.csproj
